# Form implementation generated from reading ui file 'AddClan.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddClanDialog(object):
    def setupUi(self, AddClanDialog):
        AddClanDialog.setObjectName("AddClanDialog")
        AddClanDialog.resize(350, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddClanDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=AddClanDialog)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditTag = QtWidgets.QLineEdit(parent=AddClanDialog)
        self.lineEditTag.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditTag.setObjectName("lineEditTag")
        self.horizontalLayout.addWidget(self.lineEditTag)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButtonAddClan = QtWidgets.QPushButton(parent=AddClanDialog)
        self.pushButtonAddClan.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddClan.setFont(font)
        self.pushButtonAddClan.setObjectName("pushButtonAddClan")
        self.verticalLayout.addWidget(self.pushButtonAddClan)
        self.labelResult = QtWidgets.QLabel(parent=AddClanDialog)
        self.labelResult.setMinimumSize(QtCore.QSize(0, 30))
        self.labelResult.setText("")
        self.labelResult.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)

        self.retranslateUi(AddClanDialog)
        QtCore.QMetaObject.connectSlotsByName(AddClanDialog)

    def retranslateUi(self, AddClanDialog):
        _translate = QtCore.QCoreApplication.translate
        AddClanDialog.setWindowTitle(_translate("AddClanDialog", "Dialog"))
        self.label.setText(_translate("AddClanDialog", "部落标签："))
        self.pushButtonAddClan.setText(_translate("AddClanDialog", "添加部落"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddClanDialog = QtWidgets.QDialog()
    ui = Ui_AddClanDialog()
    ui.setupUi(AddClanDialog)
    AddClanDialog.show()
    sys.exit(app.exec())
