# Form implementation generated from reading ui file 'ClanWar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClanWar(object):
    def setupUi(self, PlayerClanWar):
        PlayerClanWar.setObjectName("PlayerClanWar")
        PlayerClanWar.resize(960, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlayerClanWar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=PlayerClanWar)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 934, 614))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(PlayerClanWar)
        QtCore.QMetaObject.connectSlotsByName(PlayerClanWar)

    def retranslateUi(self, PlayerClanWar):
        _translate = QtCore.QCoreApplication.translate
        PlayerClanWar.setWindowTitle(_translate("PlayerClanWar", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlayerClanWar = QtWidgets.QWidget()
    ui = Ui_ClanWar()
    ui.setupUi(PlayerClanWar)
    PlayerClanWar.show()
    sys.exit(app.exec())
