# Form implementation generated from reading ui file 'ExportRobots.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExportRobotsDialog(object):
    def setupUi(self, ExportRobotsDialog):
        ExportRobotsDialog.setObjectName("ImportRobotsDialog")
        ExportRobotsDialog.resize(500, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExportRobotsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=ExportRobotsDialog)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButtonChooseFile = QtWidgets.QPushButton(parent=ExportRobotsDialog)
        self.pushButtonChooseFile.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonChooseFile.setFont(font)
        self.pushButtonChooseFile.setObjectName("pushButtonChooseFile")
        self.verticalLayout.addWidget(self.pushButtonChooseFile)
        self.pushButtonCommit = QtWidgets.QPushButton(parent=ExportRobotsDialog)
        self.pushButtonCommit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCommit.setFont(font)
        self.pushButtonCommit.setObjectName("pushButtonCommit")
        self.verticalLayout.addWidget(self.pushButtonCommit)

        self.retranslateUi(ExportRobotsDialog)
        QtCore.QMetaObject.connectSlotsByName(ExportRobotsDialog)

    def retranslateUi(self, ExportRobotsDialog):
        _translate = QtCore.QCoreApplication.translate
        ExportRobotsDialog.setWindowTitle(_translate("ImportRobotsDialog", "导入脚本标签文件"))
        self.pushButtonChooseFile.setText(_translate("ImportRobotsDialog", "选择文件(*.txt)"))
        self.pushButtonCommit.setText(_translate("ImportRobotsDialog", "确认"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExportRobotsDialog = QtWidgets.QDialog()
    ui = Ui_ExportRobotsDialog()
    ui.setupUi(ExportRobotsDialog)
    ExportRobotsDialog.show()
    sys.exit(app.exec())
