# Form implementation generated from reading ui file 'SelectPlayerItems.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectPlayItemsDialog(object):
    def setupUi(self, SelectPlayItemsDialog):
        SelectPlayItemsDialog.setObjectName("SelectPlayItemsDialog")
        SelectPlayItemsDialog.resize(760, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectPlayItemsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=SelectPlayItemsDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 734, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxInfo = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxInfo.setObjectName("groupBoxInfo")
        self.verticalLayout_2.addWidget(self.groupBoxInfo)
        self.groupBoxHero = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxHero.setObjectName("groupBoxHero")
        self.verticalLayout_2.addWidget(self.groupBoxHero)
        self.groupBoxTroop = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxTroop.setObjectName("groupBoxTroop")
        self.verticalLayout_2.addWidget(self.groupBoxTroop)
        self.groupBoxSpell = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxSpell.setObjectName("groupBoxSpell")
        self.verticalLayout_2.addWidget(self.groupBoxSpell)
        self.groupBoxPet = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxPet.setObjectName("groupBoxPet")
        self.verticalLayout_2.addWidget(self.groupBoxPet)
        self.groupBoxEquipment = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxEquipment.setObjectName("groupBoxEquipment")
        self.verticalLayout_2.addWidget(self.groupBoxEquipment)
        self.groupBoxBuilder = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxBuilder.setObjectName("groupBoxBuilder")
        self.verticalLayout_2.addWidget(self.groupBoxBuilder)
        self.groupBoxAchievements = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxAchievements.setObjectName("groupBoxAchievements")
        self.verticalLayout_2.addWidget(self.groupBoxAchievements)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayoutCommit = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCommit.setObjectName("horizontalLayoutCommit")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayoutCommit.addItem(spacerItem)
        self.pushButtonCommit = QtWidgets.QPushButton(parent=SelectPlayItemsDialog)
        self.pushButtonCommit.setMinimumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCommit.setFont(font)
        self.pushButtonCommit.setAutoDefault(True)
        self.pushButtonCommit.setObjectName("pushButtonCommit")
        self.horizontalLayoutCommit.addWidget(self.pushButtonCommit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayoutCommit.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayoutCommit)

        self.retranslateUi(SelectPlayItemsDialog)
        QtCore.QMetaObject.connectSlotsByName(SelectPlayItemsDialog)

    def retranslateUi(self, SelectPlayItemsDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectPlayItemsDialog.setWindowTitle(_translate("SelectPlayItemsDialog", "选择属性"))
        self.groupBoxInfo.setTitle(_translate("SelectPlayItemsDialog", "基本信息"))
        self.groupBoxHero.setTitle(_translate("SelectPlayItemsDialog", "英雄"))
        self.groupBoxTroop.setTitle(_translate("SelectPlayItemsDialog", "兵种"))
        self.groupBoxSpell.setTitle(_translate("SelectPlayItemsDialog", "法术"))
        self.groupBoxPet.setTitle(_translate("SelectPlayItemsDialog", "宠物"))
        self.groupBoxEquipment.setTitle(_translate("SelectPlayItemsDialog", "装备"))
        self.groupBoxBuilder.setTitle(_translate("SelectPlayItemsDialog", "夜世界"))
        self.groupBoxAchievements.setTitle(_translate("SelectPlayItemsDialog", "成就"))
        self.pushButtonCommit.setText(_translate("SelectPlayItemsDialog", "提交"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectPlayItemsDialog = QtWidgets.QDialog()
    ui = Ui_SelectPlayItemsDialog()
    ui.setupUi(SelectPlayItemsDialog)
    SelectPlayItemsDialog.show()
    sys.exit(app.exec())
