# Form implementation generated from reading ui file 'ShowFigures.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ShowFiguresForm(object):
    def setupUi(self, ShowFiguresForm):
        ShowFiguresForm.setObjectName("ShowFiguresForm")
        ShowFiguresForm.resize(900, 675)
        self.verticalLayout = QtWidgets.QVBoxLayout(ShowFiguresForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=ShowFiguresForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 874, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(ShowFiguresForm)
        QtCore.QMetaObject.connectSlotsByName(ShowFiguresForm)

    def retranslateUi(self, ShowFiguresForm):
        _translate = QtCore.QCoreApplication.translate
        ShowFiguresForm.setWindowTitle(_translate("ShowFiguresForm", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShowFiguresForm = QtWidgets.QWidget()
    ui = Ui_ShowFiguresForm()
    ui.setupUi(ShowFiguresForm)
    ShowFiguresForm.show()
    sys.exit(app.exec())
