# Form implementation generated from reading ui file 'WarLog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WarLogForm(object):
    def setupUi(self, WarLogForm):
        WarLogForm.setObjectName("WarLogForm")
        WarLogForm.resize(900, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(WarLogForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=WarLogForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 874, 574))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(WarLogForm)
        QtCore.QMetaObject.connectSlotsByName(WarLogForm)

    def retranslateUi(self, WarLogForm):
        _translate = QtCore.QCoreApplication.translate
        WarLogForm.setWindowTitle(_translate("WarLogForm", "部落战日志"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WarLogForm = QtWidgets.QWidget()
    ui = Ui_WarLogForm()
    ui.setupUi(WarLogForm)
    WarLogForm.show()
    sys.exit(app.exec())
